[package]
name = "lua_rust_compiling"
version = "0.1.0"
authors = ["Luca Brugnera <luca.brugnera@gmail.com>"]
description = "Bindings for Lua"
links = "lua"
build = "lib.rs"
license = "MIT"

[dependencies]
libc = "0.2"
gcc = "0.3"

[build-dependencies]
gcc = "0.3"

[lib]
build = "lib.rs"
